Traceback (most recent call last):
  File "/home/re3-pytorch/tracker/vot.py", line 17, in <module>
    import trax
ImportError: No module named 'trax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/re3-pytorch/tracker/re3_vot_tracker.py", line 2, in <module>
    import vot
  File "/home/re3-pytorch/tracker/vot.py", line 19, in <module>
    raise Exception('TraX support not found. Please add trax module to Python path.')
Exception: TraX support not found. Please add trax module to Python path.
